// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package qcode

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id                   uint64   `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	PhoneNo              string   `protobuf:"bytes,4,opt,name=PhoneNo,proto3" json:"PhoneNo,omitempty"`
	Qcode                string   `protobuf:"bytes,5,opt,name=Qcode,proto3" json:"Qcode,omitempty"`
	Check                bool     `protobuf:"varint,6,opt,name=Check,proto3" json:"Check,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_9ed89ea8a21c6d78, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhoneNo() string {
	if m != nil {
		return m.PhoneNo
	}
	return ""
}

func (m *User) GetQcode() string {
	if m != nil {
		return m.Qcode
	}
	return ""
}

func (m *User) GetCheck() bool {
	if m != nil {
		return m.Check
	}
	return false
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_9ed89ea8a21c6d78, []int{1}
}
func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (dst *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(dst, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

type Error struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Details              string   `protobuf:"bytes,2,opt,name=Details,proto3" json:"Details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_9ed89ea8a21c6d78, []int{2}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "qcode.User")
	proto.RegisterType((*Void)(nil), "qcode.Void")
	proto.RegisterType((*Error)(nil), "qcode.error")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_9ed89ea8a21c6d78) }

var fileDescriptor_user_9ed89ea8a21c6d78 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xbb, 0xed, 0x26, 0xb6, 0x53, 0xf5, 0x30, 0x78, 0x58, 0x3c, 0xd5, 0x15, 0x25, 0x5e,
	0x82, 0x28, 0x3e, 0x80, 0xb4, 0x52, 0x7a, 0xb0, 0xc4, 0x88, 0xde, 0x63, 0x32, 0x90, 0x60, 0xea,
	0xea, 0x66, 0xe3, 0x23, 0xf8, 0xc2, 0xbe, 0x80, 0xcc, 0xc6, 0x80, 0x7a, 0xa8, 0xb7, 0xf9, 0x7e,
	0xbe, 0x64, 0xfe, 0x61, 0x01, 0xda, 0x86, 0x6c, 0xfc, 0x6a, 0x8d, 0x33, 0x18, 0xbc, 0xe5, 0xa6,
	0x20, 0xfd, 0x21, 0x40, 0x3e, 0x34, 0x64, 0x71, 0x1f, 0x86, 0xab, 0x42, 0x0d, 0x67, 0x22, 0x92,
	0xe9, 0x70, 0x55, 0x20, 0x82, 0x5c, 0x67, 0x1b, 0x52, 0x62, 0x26, 0xa2, 0x49, 0xea, 0x67, 0x3c,
	0x80, 0xe0, 0x66, 0x93, 0x55, 0xb5, 0x1a, 0xf9, 0xb0, 0x03, 0x54, 0xb0, 0x93, 0x94, 0xe6, 0x85,
	0xd6, 0x46, 0x49, 0x9f, 0xf7, 0xc8, 0xfe, 0x1d, 0x6f, 0x51, 0x41, 0xe7, 0x7b, 0xe0, 0x74, 0x5e,
	0x52, 0xfe, 0xac, 0xc2, 0x99, 0x88, 0xc6, 0x69, 0x07, 0x3a, 0x04, 0xf9, 0x68, 0xaa, 0x42, 0x5f,
	0x41, 0x40, 0xd6, 0x1a, 0xcb, 0x05, 0xe6, 0xfc, 0x2d, 0x17, 0xd8, 0x4b, 0xfd, 0xcc, 0xab, 0x16,
	0xe4, 0xb2, 0xaa, 0x6e, 0x7c, 0xd3, 0x49, 0xda, 0xe3, 0xc5, 0xa7, 0x80, 0x29, 0xdf, 0x71, 0x4f,
	0xf6, 0xbd, 0xca, 0x09, 0x4f, 0x21, 0x5c, 0x92, 0xbb, 0xae, 0x6b, 0x9c, 0xc6, 0xfe, 0xd2, 0x98,
	0xff, 0x7e, 0xd8, 0x03, 0xab, 0x7a, 0x70, 0x2e, 0xf0, 0x08, 0x46, 0x4b, 0x72, 0xf8, 0x33, 0xff,
	0x23, 0xe1, 0x19, 0x8c, 0x13, 0xd3, 0xb8, 0xdb, 0x36, 0x2f, 0x7f, 0x7b, 0xbb, 0xdf, 0xe0, 0xfb,
	0xea, 0x41, 0x24, 0xf0, 0x18, 0x24, 0xab, 0x5b, 0x35, 0xd4, 0x30, 0x4a, 0xda, 0x7f, 0x9c, 0x13,
	0x08, 0x17, 0x54, 0x93, 0xa3, 0xad, 0xda, 0x53, 0xe8, 0xdf, 0xf2, 0xf2, 0x2b, 0x00, 0x00, 0xff,
	0xff, 0x72, 0xc7, 0x0b, 0xac, 0xd9, 0x01, 0x00, 0x00,
}
